[2024-11-29T14:33:03.011+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-29T14:33:03.019+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_marketplace_dag.run_dbt_models manual__2024-11-29T14:33:02.319423+00:00 [queued]>
[2024-11-29T14:33:03.022+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_marketplace_dag.run_dbt_models manual__2024-11-29T14:33:02.319423+00:00 [queued]>
[2024-11-29T14:33:03.022+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-29T14:33:03.027+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_dbt_models> on 2024-11-29 14:33:02.319423+00:00
[2024-11-29T14:33:03.030+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=494) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-29T14:33:03.031+0000] {standard_task_runner.py:72} INFO - Started process 495 to run task
[2024-11-29T14:33:03.031+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_marketplace_dag', 'run_dbt_models', 'manual__2024-11-29T14:33:02.319423+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/test/test.py', '--cfg-path', '/tmp/tmp3yt9ekl5']
[2024-11-29T14:33:03.032+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask run_dbt_models
[2024-11-29T14:33:03.054+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_marketplace_dag.run_dbt_models manual__2024-11-29T14:33:02.319423+00:00 [running]> on host 85c13f869fef
[2024-11-29T14:33:03.088+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_marketplace_dag' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T14:33:02.319423+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-29T14:33:02.319423+00:00'
[2024-11-29T14:33:03.089+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-29T14:33:03.107+0000] {docker.py:367} INFO - Starting docker container from image dbt_marketplace_image
[2024-11-29T14:33:03.992+0000] {docker.py:438} INFO - [0m14:33:03  Running with dbt=1.8.9
[2024-11-29T14:33:04.101+0000] {docker.py:438} INFO - [0m14:33:04  Registered adapter: postgres=1.8.2
[2024-11-29T14:33:04.205+0000] {docker.py:438} INFO - [0m14:33:04  Unable to do partial parsing because profile has changed
[2024-11-29T14:33:04.778+0000] {docker.py:438} INFO - [0m14:33:04  [[33mWARNING[0m]: Did not find matching node for patch with name 'stg_brand' in the 'models' section of file 'models/staging/brands/schema.yml'
[2024-11-29T14:33:04.783+0000] {docker.py:438} INFO - [0m14:33:04  [[33mWARNING[0m]: Test 'test.dbt_marketplace.unique_stg_brand_id.740741dc9f' (models/staging/brands/schema.yml) depends on a node named 'stg_brand' in package '' which was not found
[2024-11-29T14:33:04.783+0000] {docker.py:438} INFO - [0m14:33:04  [[33mWARNING[0m]: Test 'test.dbt_marketplace.not_null_stg_brand_id.c78a0edd5d' (models/staging/brands/schema.yml) depends on a node named 'stg_brand' in package '' which was not found
[2024-11-29T14:33:04.912+0000] {docker.py:438} INFO - [0m14:33:04  Found 2 models, 2 data tests, 1 source, 429 macros
[2024-11-29T14:33:04.914+0000] {docker.py:438} INFO - [0m14:33:04
[2024-11-29T14:33:05.000+0000] {docker.py:438} INFO - [0m14:33:04  Concurrency: 1 threads (target='dev')
[2024-11-29T14:33:05.001+0000] {docker.py:438} INFO - [0m14:33:04
[2024-11-29T14:33:05.005+0000] {docker.py:438} INFO - [0m14:33:05  1 of 1 START sql table model staging.staging_brand ............................. [RUN]
[2024-11-29T14:33:05.077+0000] {docker.py:438} INFO - [0m14:33:05  1 of 1 OK created sql table model staging.staging_brand ........................ [[32mSELECT 100[0m in 0.07s]
[2024-11-29T14:33:05.082+0000] {docker.py:438} INFO - [0m14:33:05
[2024-11-29T14:33:05.082+0000] {docker.py:438} INFO - [0m14:33:05  Finished running 1 table model in 0 hours 0 minutes and 0.17 seconds (0.17s).
[2024-11-29T14:33:05.100+0000] {docker.py:438} INFO - [0m14:33:05
[2024-11-29T14:33:05.101+0000] {docker.py:438} INFO - [0m14:33:05  [32mCompleted successfully[0m
[2024-11-29T14:33:05.101+0000] {docker.py:438} INFO - [0m14:33:05
[2024-11-29T14:33:05.101+0000] {docker.py:438} INFO - [0m14:33:05  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-11-29T14:33:05.818+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-29T14:33:05.818+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_marketplace_dag, task_id=run_dbt_models, run_id=manual__2024-11-29T14:33:02.319423+00:00, execution_date=20241129T143302, start_date=20241129T143303, end_date=20241129T143305
[2024-11-29T14:33:05.844+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-29T14:33:05.854+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T14:33:05.855+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
